/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ClaimResult = {
    'success' : {
      'tokensClaimed' : bigint,
      'newBalance' : bigint,
      'nextClaimTime' : Time,
    }
  } |
  { 'mintFailed' : string } |
  { 'cooldown' : { 'currentBalance' : bigint, 'remainingTime' : bigint } } |
  { 'insufficientCharge' : { 'required' : bigint, 'current' : bigint } };
export interface Coordinates { 'lat' : number, 'lon' : number }
export type DiscoverCacheResult = { 'success' : LootCache } |
  { 'insufficientTokens' : { 'required' : bigint, 'current' : bigint } } |
  { 'paymentFailed' : string } |
  { 'insufficientCharge' : { 'required' : bigint, 'current' : bigint } };
export interface LandData {
  'decorationURL' : [] | [string],
  'baseTokenMultiplier' : number,
  'lastChargeUpdate' : Time,
  'upgradeLevel' : bigint,
  'principal' : Principal,
  'landId' : bigint,
  'lastClaimTime' : Time,
  'biome' : string,
  'chargeCap' : bigint,
  'cycleCharge' : bigint,
  'plotName' : string,
  'coordinates' : Coordinates,
  'attachedModifications' : Array<ModifierInstance>,
}
export interface LootCache {
  'owner' : Principal,
  'tier' : bigint,
  'cache_id' : bigint,
  'discovered_at' : Time,
  'is_opened' : boolean,
}
export interface Modification {
  'model_url' : string,
  'mod_id' : bigint,
  'rarity_tier' : bigint,
  'multiplier_value' : number,
}
export interface Modifier {
  'name' : string,
  'asset_url' : string,
  'mod_id' : bigint,
  'rarity_tier' : bigint,
  'multiplier_value' : number,
}
export interface ModifierInstance {
  'modifierInstanceId' : bigint,
  'modifierType' : string,
  'model_url' : string,
  'rarity_tier' : bigint,
  'multiplier_value' : number,
}
export interface PublicLandInfo {
  'landId' : bigint,
  'biome' : string,
  'principal' : Principal,
}
export type Time = bigint;
export interface TopLandEntry {
  'upgradeLevel' : bigint,
  'principal' : Principal,
  'tokenBalance' : bigint,
  'plotName' : string,
  'biome' : string,
  'landId' : bigint,
}
export type UpgradeResult = { 'maxLevelReached' : null } |
  { 'success' : { 'newLevel' : bigint, 'remainingTokens' : bigint } } |
  { 'insufficientTokens' : { 'required' : bigint, 'current' : bigint } };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type CrystalKind = { 'Burnite' : null } | { 'Synthex' : null } | { 'Cryonix' : null };
export type CrystalTier = { 'T1' : null } | { 'T2' : null };
export interface CrystalItem { 'kind' : CrystalKind, 'tier' : CrystalTier, 'quantity' : bigint }
export type BoosterKind = { 'B250' : null } | { 'B500' : null } | { 'B1000' : null };
export interface BoosterItem { 'kind' : BoosterKind, 'quantity' : bigint }
export interface KeeperHeartItem { 'biome' : string }
export interface CacheDropMod { 'modId' : bigint, 'rarityTier' : bigint, 'subtype' : string, 'instanceId' : bigint }
export type CacheDropItem =
  { 'mod' : CacheDropMod } |
  { 'crystal' : CrystalItem } |
  { 'booster' : BoosterItem } |
  { 'keeperHeart' : KeeperHeartItem };
export interface CacheOpenResult { 'items' : Array<CacheDropItem>, 'energySpent' : bigint }
export interface FullInventory { 'crystals' : Array<CrystalItem>, 'boosters' : Array<BoosterItem>, 'keeperHearts' : Array<KeeperHeartItem> }
export type ItemType = { 'Land' : null } | { 'Modifier' : null };
export interface Listing {
  'listingId' : bigint,
  'itemId' : bigint,
  'itemType' : ItemType,
  'seller' : Principal,
  'price' : bigint,
  'isActive' : boolean,
}
export interface _SERVICE {
  'adminGetLandData' : ActorMethod<[Principal], [] | [Array<LandData>]>,
  'adminSetAllModifiers' : ActorMethod<[Array<Modifier>], undefined>,
  'applyModifier' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimRewards' : ActorMethod<[bigint], ClaimResult>,
  'discoverLootCache' : ActorMethod<[bigint], DiscoverCacheResult>,
  'getAllLandsPublic' : ActorMethod<[], Array<PublicLandInfo>>,
  'getAllModifiers' : ActorMethod<[], Array<Modifier>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLandData' : ActorMethod<[], Array<LandData>>,
  'getLandDataById' : ActorMethod<[bigint], [] | [LandData]>,
  'getLandDataQuery' : ActorMethod<[], [] | [Array<LandData>]>,
  'getLandOwner' : ActorMethod<[bigint], [] | [Principal]>,
  'getModifierById' : ActorMethod<[bigint], [] | [Modifier]>,
  'getModifiersByTier' : ActorMethod<[bigint], Array<Modifier>>,
  'getMyLootCaches' : ActorMethod<[], Array<LootCache>>,
  'getMyModifierInventory' : ActorMethod<[], Array<ModifierInstance>>,
  'getTopLands' : ActorMethod<[bigint], Array<TopLandEntry>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'mintLand' : ActorMethod<[], LandData>,
  'processCache' : ActorMethod<[bigint], ModifierInstance>,
  'openCache' : ActorMethod<[bigint], CacheOpenResult>,
  'useBooster' : ActorMethod<[BoosterKind], undefined>,
  'getFullInventory' : ActorMethod<[], FullInventory>,
  'removeModifier' : ActorMethod<[bigint, bigint], undefined>,
  'setGovernanceCanister' : ActorMethod<[Principal], undefined>,
  'setMarketplaceCanister' : ActorMethod<[Principal], undefined>,
  'setTokenCanister' : ActorMethod<[Principal], undefined>,
  'transferLand' : ActorMethod<[Principal, bigint], boolean>,
  'transferModifier' : ActorMethod<[Principal, Principal, bigint], boolean>,
  'upgradePlot' : ActorMethod<[bigint, bigint], UpgradeResult>,
  // Built-in marketplace
  'list_item' : ActorMethod<[bigint, ItemType, bigint], bigint>,
  'buy_item' : ActorMethod<[bigint], boolean>,
  'cancelListing' : ActorMethod<[bigint], boolean>,
  'getAllActiveListings' : ActorMethod<[], Array<Listing>>,
  'getUserListings' : ActorMethod<[Principal], Array<Listing>>,
  'getActiveListing' : ActorMethod<[bigint], [] | [Listing]>,
  // Governance
  'gStakeTokens' : ActorMethod<[bigint], any>,
  'gUnstakeTokens' : ActorMethod<[bigint], undefined>,
  'gClaimVestedRewards' : ActorMethod<[], bigint>,
  'gGetMyStakeInfo' : ActorMethod<[], any>,
  'gGetStakedBalance' : ActorMethod<[Principal], bigint>,
  'gGetTotalWeightedStake' : ActorMethod<[], bigint>,
  'gReceiveIncome' : ActorMethod<[bigint], undefined>,
  'gGetTreasuryBalance' : ActorMethod<[], bigint>,
  'gGetDeveloperFund' : ActorMethod<[], bigint>,
  'gGetInsuranceReserve' : ActorMethod<[], bigint>,
  'gCreateProposal' : ActorMethod<[string, string, string], bigint>,
  'gVote' : ActorMethod<[bigint, boolean], any>,
  'gGetAllProposals' : ActorMethod<[], Array<any>>,
  'gGetActiveProposals' : ActorMethod<[], Array<any>>,
  'gGetMyVotes' : ActorMethod<[], Array<any>>,
  'gGetLeaderboard' : ActorMethod<[bigint], Array<any>>,
  'gCalcWeight' : ActorMethod<[Principal], bigint>,
  'gAdminCloseProposal' : ActorMethod<[bigint], undefined>,
  'gAdminWithdrawTreasury' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
