/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ClaimResult = {
    'success' : {
      'tokensClaimed' : bigint,
      'newBalance' : bigint,
      'nextClaimTime' : Time,
    }
  } |
  { 'mintFailed' : string } |
  { 'cooldown' : { 'currentBalance' : bigint, 'remainingTime' : bigint } } |
  { 'insufficientCharge' : { 'required' : bigint, 'current' : bigint } };
export interface Coordinates { 'lat' : number, 'lon' : number }
export type DiscoverCacheResult = { 'success' : LootCache } |
  { 'insufficientTokens' : { 'required' : bigint, 'current' : bigint } } |
  { 'paymentFailed' : string } |
  { 'insufficientCharge' : { 'required' : bigint, 'current' : bigint } };
export interface LandData {
  'decorationURL' : [] | [string],
  'baseTokenMultiplier' : number,
  'lastChargeUpdate' : Time,
  'upgradeLevel' : bigint,
  'principal' : Principal,
  'landId' : bigint,
  'lastClaimTime' : Time,
  'biome' : string,
  'chargeCap' : bigint,
  'cycleCharge' : bigint,
  'plotName' : string,
  'coordinates' : Coordinates,
  'attachedModifications' : Array<ModifierInstance>,
}
export interface LootCache {
  'owner' : Principal,
  'tier' : bigint,
  'cache_id' : bigint,
  'discovered_at' : Time,
  'is_opened' : boolean,
}
export interface Modification {
  'model_url' : string,
  'mod_id' : bigint,
  'rarity_tier' : bigint,
  'multiplier_value' : number,
}
export interface Modifier {
  'name' : string,
  'asset_url' : string,
  'mod_id' : bigint,
  'rarity_tier' : bigint,
  'multiplier_value' : number,
}
export interface ModifierInstance {
  'modifierInstanceId' : bigint,
  'modifierType' : string,
  'model_url' : string,
  'rarity_tier' : bigint,
  'multiplier_value' : number,
}
export interface PublicLandInfo {
  'landId' : bigint,
  'biome' : string,
  'principal' : Principal,
}
export type Time = bigint;
export interface TopLandEntry {
  'upgradeLevel' : bigint,
  'principal' : Principal,
  'tokenBalance' : bigint,
  'plotName' : string,
  'biome' : string,
  'landId' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UpgradeResult = { 'maxLevelReached' : null } |
  { 'success' : { 'newLevel' : bigint, 'remainingTokens' : bigint } } |
  { 'insufficientTokens' : { 'required' : bigint, 'current' : bigint } };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type CrystalKind = { 'Burnite' : null } | { 'Synthex' : null } | { 'Cryonix' : null };
export type CrystalTier = { 'T1' : null } | { 'T2' : null };
export interface CrystalItem { 'kind' : CrystalKind, 'tier' : CrystalTier, 'quantity' : bigint }
export type BoosterKind = { 'B250' : null } | { 'B500' : null } | { 'B1000' : null };
export interface BoosterItem { 'kind' : BoosterKind, 'quantity' : bigint }
export interface KeeperHeartItem { 'biome' : string }
export interface CacheDropMod { 'modId' : bigint, 'rarityTier' : bigint, 'subtype' : string, 'instanceId' : bigint }
export type CacheDropItem =
  { 'mod' : CacheDropMod } |
  { 'crystal' : CrystalItem } |
  { 'booster' : BoosterItem } |
  { 'keeperHeart' : KeeperHeartItem };
export interface CacheOpenResult { 'items' : Array<CacheDropItem>, 'energySpent' : bigint }
export interface FullInventory { 'crystals' : Array<CrystalItem>, 'boosters' : Array<BoosterItem>, 'keeperHearts' : Array<KeeperHeartItem> }
export interface _SERVICE {
  'adminGetLandData' : ActorMethod<[Principal], [] | [Array<LandData>]>,
  'adminSetAllModifiers' : ActorMethod<[Array<Modifier>], undefined>,
  'applyModifier' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimRewards' : ActorMethod<[bigint], ClaimResult>,
  'discoverLootCache' : ActorMethod<[bigint], DiscoverCacheResult>,
  'getAllLandsPublic' : ActorMethod<[], Array<PublicLandInfo>>,
  'getAllModifiers' : ActorMethod<[], Array<Modifier>>,
  'getAssetCanisterCycleBalance' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentCbrBalance' : ActorMethod<[], bigint>,
  'getHighestRarityModification' : ActorMethod<[], [] | [Modification]>,
  'getLandCanisterCycleBalance' : ActorMethod<[], string>,
  'getLandData' : ActorMethod<[], Array<LandData>>,
  'getLandDataQuery' : ActorMethod<[], [] | [Array<LandData>]>,
  'getLandOwner' : ActorMethod<[bigint], [] | [Principal]>,
  'getModifierById' : ActorMethod<[bigint], [] | [Modifier]>,
  'getModifiersByTier' : ActorMethod<[bigint], Array<Modifier>>,
  'getMyLootCaches' : ActorMethod<[], Array<LootCache>>,
  'getMyModifications' : ActorMethod<[], Array<Modification>>,
  'getMyModifierInventory' : ActorMethod<[], Array<ModifierInstance>>,
  'getTopLands' : ActorMethod<[bigint], Array<TopLandEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'mintLand' : ActorMethod<[], LandData>,
  'processCache' : ActorMethod<[bigint], ModifierInstance>,
  'openCache' : ActorMethod<[bigint], CacheOpenResult>,
  'useBooster' : ActorMethod<[BoosterKind], undefined>,
  'getFullInventory' : ActorMethod<[], FullInventory>,

  'removeModifier' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setGovernanceCanister' : ActorMethod<[Principal], undefined>,
  'setMarketplaceCanister' : ActorMethod<[Principal], undefined>,
  'setTokenCanister' : ActorMethod<[Principal], undefined>,
  'transferLand' : ActorMethod<[Principal, bigint], boolean>,
  'transferModifier' : ActorMethod<[Principal, Principal, bigint], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDecoration' : ActorMethod<[bigint, string], undefined>,
  'updatePlotName' : ActorMethod<[bigint, string], undefined>,
  'upgradePlot' : ActorMethod<[bigint, bigint], UpgradeResult>,
  'useConsumableBuff' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
