/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Coordinates = IDL.Record({
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
});
export const ModifierInstance = IDL.Record({
  'modifierInstanceId' : IDL.Nat,
  'modifierType' : IDL.Text,
  'model_url' : IDL.Text,
  'rarity_tier' : IDL.Nat,
  'multiplier_value' : IDL.Float64,
});
export const LandData = IDL.Record({
  'decorationURL' : IDL.Opt(IDL.Text),
  'baseTokenMultiplier' : IDL.Float64,
  'lastChargeUpdate' : Time,
  'upgradeLevel' : IDL.Nat,
  'principal' : IDL.Principal,
  'landId' : IDL.Nat,
  'lastClaimTime' : Time,
  'biome' : IDL.Text,
  'chargeCap' : IDL.Nat,
  'cycleCharge' : IDL.Int,
  'plotName' : IDL.Text,
  'coordinates' : Coordinates,
  'attachedModifications' : IDL.Vec(ModifierInstance),
});
export const Modifier = IDL.Record({
  'name' : IDL.Text,
  'asset_url' : IDL.Text,
  'mod_id' : IDL.Nat,
  'rarity_tier' : IDL.Nat,
  'multiplier_value' : IDL.Float64,
});
export const PublicLandInfo = IDL.Record({
  'landId' : IDL.Nat,
  'biome' : IDL.Text,
  'principal' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClaimResult = IDL.Variant({
  'success' : IDL.Record({
    'tokensClaimed' : IDL.Nat,
    'newBalance' : IDL.Nat,
    'nextClaimTime' : Time,
  }),
  'mintFailed' : IDL.Text,
  'cooldown' : IDL.Record({
    'currentBalance' : IDL.Nat,
    'remainingTime' : IDL.Int,
  }),
  'insufficientCharge' : IDL.Record({
    'required' : IDL.Nat,
    'current' : IDL.Int,
  }),
});
export const LootCache = IDL.Record({
  'owner' : IDL.Principal,
  'tier' : IDL.Nat,
  'cache_id' : IDL.Nat,
  'discovered_at' : Time,
  'is_opened' : IDL.Bool,
});
export const DiscoverCacheResult = IDL.Variant({
  'success' : LootCache,
  'insufficientTokens' : IDL.Record({
    'required' : IDL.Nat,
    'current' : IDL.Nat,
  }),
  'paymentFailed' : IDL.Text,
  'insufficientCharge' : IDL.Record({
    'required' : IDL.Nat,
    'current' : IDL.Int,
  }),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TopLandEntry = IDL.Record({
  'upgradeLevel' : IDL.Nat,
  'principal' : IDL.Principal,
  'tokenBalance' : IDL.Nat,
  'plotName' : IDL.Text,
  'biome' : IDL.Text,
  'landId' : IDL.Nat,
});
export const UpgradeResult = IDL.Variant({
  'maxLevelReached' : IDL.Null,
  'success' : IDL.Record({ 'newLevel' : IDL.Nat, 'remainingTokens' : IDL.Nat }),
  'insufficientTokens' : IDL.Record({
    'required' : IDL.Nat,
    'current' : IDL.Nat,
  }),
});

export const CrystalKind = IDL.Variant({ 'Burnite': IDL.Null, 'Synthex': IDL.Null, 'Cryonix': IDL.Null });
export const CrystalTier = IDL.Variant({ 'T1': IDL.Null, 'T2': IDL.Null });
export const CrystalItem = IDL.Record({ 'kind': CrystalKind, 'tier': CrystalTier, 'quantity': IDL.Nat });
export const BoosterKind = IDL.Variant({ 'B250': IDL.Null, 'B500': IDL.Null, 'B1000': IDL.Null });
export const BoosterItem = IDL.Record({ 'kind': BoosterKind, 'quantity': IDL.Nat });
export const KeeperHeartItem = IDL.Record({ 'biome': IDL.Text });
export const CacheDropMod = IDL.Record({ 'modId': IDL.Nat, 'rarityTier': IDL.Nat, 'subtype': IDL.Text, 'instanceId': IDL.Nat });
export const CacheDropItem = IDL.Variant({
  'mod': CacheDropMod,
  'crystal': CrystalItem,
  'booster': BoosterItem,
  'keeperHeart': KeeperHeartItem,
});
export const CacheOpenResult = IDL.Record({ 'items': IDL.Vec(CacheDropItem), 'energySpent': IDL.Nat });
export const FullInventory = IDL.Record({ 'crystals': IDL.Vec(CrystalItem), 'boosters': IDL.Vec(BoosterItem), 'keeperHearts': IDL.Vec(KeeperHeartItem) });

export const ItemType = IDL.Variant({ 'Land': IDL.Null, 'Modifier': IDL.Null });
export const Listing = IDL.Record({
  'listingId': IDL.Nat,
  'itemId': IDL.Nat,
  'itemType': ItemType,
  'seller': IDL.Principal,
  'price': IDL.Nat,
  'isActive': IDL.Bool,
});

export const idlService = IDL.Service({
  'adminGetLandData' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Vec(LandData))], ['query']),
  'adminSetAllModifiers' : IDL.Func([IDL.Vec(Modifier)], [], []),
  'applyModifier' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimRewards' : IDL.Func([IDL.Nat], [ClaimResult], []),
  'discoverLootCache' : IDL.Func([IDL.Nat], [DiscoverCacheResult], []),
  'getAllLandsPublic' : IDL.Func([], [IDL.Vec(PublicLandInfo)], ['query']),
  'getAllModifiers' : IDL.Func([], [IDL.Vec(Modifier)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLandData' : IDL.Func([], [IDL.Vec(LandData)], []),
  'getLandDataById' : IDL.Func([IDL.Nat], [IDL.Opt(LandData)], ['query']),
  'getLandDataQuery' : IDL.Func([], [IDL.Opt(IDL.Vec(LandData))], ['query']),
  'getLandOwner' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Principal)], ['query']),
  'getModifierById' : IDL.Func([IDL.Nat], [IDL.Opt(Modifier)], ['query']),
  'getModifiersByTier' : IDL.Func([IDL.Nat], [IDL.Vec(Modifier)], ['query']),
  'getMyLootCaches' : IDL.Func([], [IDL.Vec(LootCache)], ['query']),
  'getMyModifierInventory' : IDL.Func([], [IDL.Vec(ModifierInstance)], ['query']),
  'getTopLands' : IDL.Func([IDL.Nat], [IDL.Vec(TopLandEntry)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'mintLand' : IDL.Func([], [LandData], []),
  'processCache' : IDL.Func([IDL.Nat], [ModifierInstance], []),
  'openCache' : IDL.Func([IDL.Nat], [CacheOpenResult], []),
  'useBooster' : IDL.Func([BoosterKind], [], []),
  'getFullInventory' : IDL.Func([], [FullInventory], ['query']),
  'removeModifier' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setGovernanceCanister' : IDL.Func([IDL.Principal], [], []),
  'setMarketplaceCanister' : IDL.Func([IDL.Principal], [], []),
  'setTokenCanister' : IDL.Func([IDL.Principal], [], []),
  'transferLand' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], []),
  'transferModifier' : IDL.Func([IDL.Principal, IDL.Principal, IDL.Nat], [IDL.Bool], []),
  'upgradePlot' : IDL.Func([IDL.Nat, IDL.Nat], [UpgradeResult], []),
  // Built-in marketplace
  'list_item' : IDL.Func([IDL.Nat, ItemType, IDL.Nat], [IDL.Nat], []),
  'buy_item' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'cancelListing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getUserListings' : IDL.Func([IDL.Principal], [IDL.Vec(Listing)], ['query']),
  'getActiveListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  // Governance
  'gStakeTokens' : IDL.Func([IDL.Nat], [IDL.Variant({ 'success': IDL.Record({ 'newStake': IDL.Nat }), 'insufficientTokens': IDL.Record({ 'required': IDL.Nat, 'available': IDL.Nat }), 'transferFailed': IDL.Text })], []),
  'gUnstakeTokens' : IDL.Func([IDL.Nat], [], []),
  'gClaimVestedRewards' : IDL.Func([], [IDL.Nat], []),
  'gGetMyStakeInfo' : IDL.Func([], [IDL.Record({ 'stake': IDL.Nat, 'lockEndsAt': Time, 'weight': IDL.Nat, 'unclaimedRewards': IDL.Nat, 'claimableVest': IDL.Nat, 'pendingVest': IDL.Nat })], ['query']),
  'gGetStakedBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'gGetTotalWeightedStake' : IDL.Func([], [IDL.Nat], ['query']),
  'gReceiveIncome' : IDL.Func([IDL.Nat], [], []),
  'gGetTreasuryBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'gGetDeveloperFund' : IDL.Func([], [IDL.Nat], ['query']),
  'gGetInsuranceReserve' : IDL.Func([], [IDL.Nat], ['query']),
  'gCreateProposal' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'gVote' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Variant({ 'success': IDL.Record({ 'weight': IDL.Nat }), 'proposalNotFound': IDL.Null, 'proposalNotActive': IDL.Null, 'alreadyVoted': IDL.Null, 'notStaker': IDL.Null })], []),
  'gGetAllProposals' : IDL.Func([], [IDL.Vec(IDL.Record({ 'id': IDL.Nat, 'title': IDL.Text, 'description': IDL.Text, 'category': IDL.Text, 'proposer': IDL.Principal, 'createdAt': Time, 'votesYes': IDL.Nat, 'votesNo': IDL.Nat, 'isActive': IDL.Bool }))], ['query']),
  'gGetActiveProposals' : IDL.Func([], [IDL.Vec(IDL.Record({ 'id': IDL.Nat, 'title': IDL.Text, 'description': IDL.Text, 'category': IDL.Text, 'proposer': IDL.Principal, 'createdAt': Time, 'votesYes': IDL.Nat, 'votesNo': IDL.Nat, 'isActive': IDL.Bool }))], ['query']),
  'gGetMyVotes' : IDL.Func([], [IDL.Vec(IDL.Record({ 'proposalId': IDL.Nat, 'choice': IDL.Bool, 'weight': IDL.Nat }))], ['query']),
  'gGetLeaderboard' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Record({ 'principal': IDL.Principal, 'stake': IDL.Nat, 'weight': IDL.Nat, 'topBiome': IDL.Text, 'maxMods': IDL.Nat, 'unclaimedRewards': IDL.Nat }))], ['query']),
  'gCalcWeight' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'gAdminCloseProposal' : IDL.Func([IDL.Nat], [], []),
  'gAdminWithdrawTreasury' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Coordinates = IDL.Record({ 'lat' : IDL.Float64, 'lon' : IDL.Float64 });
  const ModifierInstance = IDL.Record({
    'modifierInstanceId' : IDL.Nat,
    'modifierType' : IDL.Text,
    'model_url' : IDL.Text,
    'rarity_tier' : IDL.Nat,
    'multiplier_value' : IDL.Float64,
  });
  const LandData = IDL.Record({
    'decorationURL' : IDL.Opt(IDL.Text),
    'baseTokenMultiplier' : IDL.Float64,
    'lastChargeUpdate' : Time,
    'upgradeLevel' : IDL.Nat,
    'principal' : IDL.Principal,
    'landId' : IDL.Nat,
    'lastClaimTime' : Time,
    'biome' : IDL.Text,
    'chargeCap' : IDL.Nat,
    'cycleCharge' : IDL.Int,
    'plotName' : IDL.Text,
    'coordinates' : Coordinates,
    'attachedModifications' : IDL.Vec(ModifierInstance),
  });
  const Modifier = IDL.Record({
    'name' : IDL.Text,
    'asset_url' : IDL.Text,
    'mod_id' : IDL.Nat,
    'rarity_tier' : IDL.Nat,
    'multiplier_value' : IDL.Float64,
  });
  const PublicLandInfo = IDL.Record({
    'landId' : IDL.Nat,
    'biome' : IDL.Text,
    'principal' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClaimResult = IDL.Variant({
    'success' : IDL.Record({
      'tokensClaimed' : IDL.Nat,
      'newBalance' : IDL.Nat,
      'nextClaimTime' : Time,
    }),
    'mintFailed' : IDL.Text,
    'cooldown' : IDL.Record({
      'currentBalance' : IDL.Nat,
      'remainingTime' : IDL.Int,
    }),
    'insufficientCharge' : IDL.Record({
      'required' : IDL.Nat,
      'current' : IDL.Int,
    }),
  });
  const LootCache = IDL.Record({
    'owner' : IDL.Principal,
    'tier' : IDL.Nat,
    'cache_id' : IDL.Nat,
    'discovered_at' : Time,
    'is_opened' : IDL.Bool,
  });
  const DiscoverCacheResult = IDL.Variant({
    'success' : LootCache,
    'insufficientTokens' : IDL.Record({
      'required' : IDL.Nat,
      'current' : IDL.Nat,
    }),
    'paymentFailed' : IDL.Text,
    'insufficientCharge' : IDL.Record({
      'required' : IDL.Nat,
      'current' : IDL.Int,
    }),
  });
  const TopLandEntry = IDL.Record({
    'upgradeLevel' : IDL.Nat,
    'principal' : IDL.Principal,
    'tokenBalance' : IDL.Nat,
    'plotName' : IDL.Text,
    'biome' : IDL.Text,
    'landId' : IDL.Nat,
  });
  const UpgradeResult = IDL.Variant({
    'maxLevelReached' : IDL.Null,
    'success' : IDL.Record({
      'newLevel' : IDL.Nat,
      'remainingTokens' : IDL.Nat,
    }),
    'insufficientTokens' : IDL.Record({
      'required' : IDL.Nat,
      'current' : IDL.Nat,
    }),
  });
  const CrystalKind = IDL.Variant({ 'Burnite': IDL.Null, 'Synthex': IDL.Null, 'Cryonix': IDL.Null });
  const CrystalTier = IDL.Variant({ 'T1': IDL.Null, 'T2': IDL.Null });
  const CrystalItem = IDL.Record({ 'kind': CrystalKind, 'tier': CrystalTier, 'quantity': IDL.Nat });
  const BoosterKind = IDL.Variant({ 'B250': IDL.Null, 'B500': IDL.Null, 'B1000': IDL.Null });
  const BoosterItem = IDL.Record({ 'kind': BoosterKind, 'quantity': IDL.Nat });
  const KeeperHeartItem = IDL.Record({ 'biome': IDL.Text });
  const CacheDropMod = IDL.Record({ 'modId': IDL.Nat, 'rarityTier': IDL.Nat, 'subtype': IDL.Text, 'instanceId': IDL.Nat });
  const CacheDropItem = IDL.Variant({
    'mod': CacheDropMod,
    'crystal': CrystalItem,
    'booster': BoosterItem,
    'keeperHeart': KeeperHeartItem,
  });
  const CacheOpenResult = IDL.Record({ 'items': IDL.Vec(CacheDropItem), 'energySpent': IDL.Nat });
  const FullInventory = IDL.Record({ 'crystals': IDL.Vec(CrystalItem), 'boosters': IDL.Vec(BoosterItem), 'keeperHearts': IDL.Vec(KeeperHeartItem) });
  const ItemType = IDL.Variant({ 'Land': IDL.Null, 'Modifier': IDL.Null });
  const Listing = IDL.Record({
    'listingId': IDL.Nat,
    'itemId': IDL.Nat,
    'itemType': ItemType,
    'seller': IDL.Principal,
    'price': IDL.Nat,
    'isActive': IDL.Bool,
  });
  
  return IDL.Service({
    'adminGetLandData' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Vec(LandData))], ['query']),
    'adminSetAllModifiers' : IDL.Func([IDL.Vec(Modifier)], [], []),
    'applyModifier' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimRewards' : IDL.Func([IDL.Nat], [ClaimResult], []),
    'discoverLootCache' : IDL.Func([IDL.Nat], [DiscoverCacheResult], []),
    'getAllLandsPublic' : IDL.Func([], [IDL.Vec(PublicLandInfo)], ['query']),
    'getAllModifiers' : IDL.Func([], [IDL.Vec(Modifier)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLandData' : IDL.Func([], [IDL.Vec(LandData)], []),
    'getLandDataById' : IDL.Func([IDL.Nat], [IDL.Opt(LandData)], ['query']),
    'getLandDataQuery' : IDL.Func([], [IDL.Opt(IDL.Vec(LandData))], ['query']),
    'getLandOwner' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Principal)], ['query']),
    'getModifierById' : IDL.Func([IDL.Nat], [IDL.Opt(Modifier)], ['query']),
    'getModifiersByTier' : IDL.Func([IDL.Nat], [IDL.Vec(Modifier)], ['query']),
    'getMyLootCaches' : IDL.Func([], [IDL.Vec(LootCache)], ['query']),
    'getMyModifierInventory' : IDL.Func([], [IDL.Vec(ModifierInstance)], ['query']),
    'getTopLands' : IDL.Func([IDL.Nat], [IDL.Vec(TopLandEntry)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'mintLand' : IDL.Func([], [LandData], []),
    'processCache' : IDL.Func([IDL.Nat], [ModifierInstance], []),
    'openCache' : IDL.Func([IDL.Nat], [CacheOpenResult], []),
    'useBooster' : IDL.Func([BoosterKind], [], []),
    'getFullInventory' : IDL.Func([], [FullInventory], ['query']),
    'removeModifier' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setGovernanceCanister' : IDL.Func([IDL.Principal], [], []),
    'setMarketplaceCanister' : IDL.Func([IDL.Principal], [], []),
    'setTokenCanister' : IDL.Func([IDL.Principal], [], []),
    'transferLand' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], []),
    'transferModifier' : IDL.Func([IDL.Principal, IDL.Principal, IDL.Nat], [IDL.Bool], []),
    'upgradePlot' : IDL.Func([IDL.Nat, IDL.Nat], [UpgradeResult], []),
    'list_item' : IDL.Func([IDL.Nat, ItemType, IDL.Nat], [IDL.Nat], []),
    'buy_item' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'cancelListing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getUserListings' : IDL.Func([IDL.Principal], [IDL.Vec(Listing)], ['query']),
    'getActiveListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'gStakeTokens' : IDL.Func([IDL.Nat], [IDL.Variant({ 'success': IDL.Record({ 'newStake': IDL.Nat }), 'insufficientTokens': IDL.Record({ 'required': IDL.Nat, 'available': IDL.Nat }), 'transferFailed': IDL.Text })], []),
    'gUnstakeTokens' : IDL.Func([IDL.Nat], [], []),
    'gClaimVestedRewards' : IDL.Func([], [IDL.Nat], []),
    'gGetMyStakeInfo' : IDL.Func([], [IDL.Record({ 'stake': IDL.Nat, 'lockEndsAt': Time, 'weight': IDL.Nat, 'unclaimedRewards': IDL.Nat, 'claimableVest': IDL.Nat, 'pendingVest': IDL.Nat })], ['query']),
    'gGetStakedBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'gGetTotalWeightedStake' : IDL.Func([], [IDL.Nat], ['query']),
    'gReceiveIncome' : IDL.Func([IDL.Nat], [], []),
    'gGetTreasuryBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'gGetDeveloperFund' : IDL.Func([], [IDL.Nat], ['query']),
    'gGetInsuranceReserve' : IDL.Func([], [IDL.Nat], ['query']),
    'gCreateProposal' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'gVote' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Variant({ 'success': IDL.Record({ 'weight': IDL.Nat }), 'proposalNotFound': IDL.Null, 'proposalNotActive': IDL.Null, 'alreadyVoted': IDL.Null, 'notStaker': IDL.Null })], []),
    'gGetAllProposals' : IDL.Func([], [IDL.Vec(IDL.Record({ 'id': IDL.Nat, 'title': IDL.Text, 'description': IDL.Text, 'category': IDL.Text, 'proposer': IDL.Principal, 'createdAt': Time, 'votesYes': IDL.Nat, 'votesNo': IDL.Nat, 'isActive': IDL.Bool }))], ['query']),
    'gGetActiveProposals' : IDL.Func([], [IDL.Vec(IDL.Record({ 'id': IDL.Nat, 'title': IDL.Text, 'description': IDL.Text, 'category': IDL.Text, 'proposer': IDL.Principal, 'createdAt': Time, 'votesYes': IDL.Nat, 'votesNo': IDL.Nat, 'isActive': IDL.Bool }))], ['query']),
    'gGetMyVotes' : IDL.Func([], [IDL.Vec(IDL.Record({ 'proposalId': IDL.Nat, 'choice': IDL.Bool, 'weight': IDL.Nat }))], ['query']),
    'gGetLeaderboard' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Record({ 'principal': IDL.Principal, 'stake': IDL.Nat, 'weight': IDL.Nat, 'topBiome': IDL.Text, 'maxMods': IDL.Nat, 'unclaimedRewards': IDL.Nat }))], ['query']),
    'gCalcWeight' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'gAdminCloseProposal' : IDL.Func([IDL.Nat], [], []),
    'gAdminWithdrawTreasury' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
