/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}

export interface ModifierInstance {
    modifierInstanceId: bigint;
    modifierType: string;
    model_url: string;
    rarity_tier: bigint;
    multiplier_value: number;
}

export interface LandData {
    landId: bigint;
    principal: Principal;
    biome: string;
    cycleCharge: bigint;
    chargeCap: bigint;
    upgradeLevel: bigint;
    baseTokenMultiplier: number;
    lastClaimTime: bigint;
    lastChargeUpdate: bigint;
    attachedModifications: ModifierInstance[];
}

export interface LootCache {
    cache_id: bigint;
    owner: Principal;
    tier: bigint;
    discovered_at: bigint;
    is_opened: boolean;
}

export type DiscoverCacheResult =
    | { __kind__: "success"; success: LootCache }
    | { __kind__: "insufficientTokens"; insufficientTokens: { required: bigint; current: bigint } }
    | { __kind__: "paymentFailed"; paymentFailed: string }
    | { __kind__: "insufficientCharge"; insufficientCharge: { required: bigint; current: bigint } };

export type ClaimResult =
    | { __kind__: "success"; success: { tokensClaimed: bigint; newBalance: bigint; nextClaimTime: bigint } }
    | { __kind__: "mintFailed"; mintFailed: string }
    | { __kind__: "cooldown"; cooldown: { currentBalance: bigint; remainingTime: bigint } }
    | { __kind__: "insufficientCharge"; insufficientCharge: { required: bigint; current: bigint } };

export type UpgradeResult =
    | { __kind__: "maxLevelReached" }
    | { __kind__: "success"; success: { newLevel: bigint; remainingTokens: bigint } }
    | { __kind__: "insufficientTokens"; insufficientTokens: { required: bigint; current: bigint } };

export type Time = bigint;

export interface TopLandEntry {
    upgradeLevel: bigint;
    principal: Principal;
    tokenBalance: bigint;
    biome: string;
    landId: bigint;
}

export interface PublicLandInfo {
    landId: bigint;
    biome: string;
    principal: Principal;
}

export interface Modifier {
    mod_id: bigint;
    rarity_tier: bigint;
    name: string;
    multiplier_value: number;
    asset_url: string;
}

export interface backendInterface {
    getLandData(): Promise<LandData[]>;
    getLandDataQuery(): Promise<LandData[] | null>;
    getCallerUserRole(): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    claimRewards(landId: bigint): Promise<ClaimResult>;
    upgradePlot(landId: bigint, cost: bigint): Promise<UpgradeResult>;
    applyModifier(modifierInstanceId: bigint, landId: bigint): Promise<void>;
    removeModifier(landId: bigint, modifierInstanceId: bigint): Promise<void>;
    mintLand(): Promise<LandData>;
    getTopLands(limit: bigint): Promise<TopLandEntry[]>;
    getMyModifierInventory(): Promise<ModifierInstance[]>;
    getMyLootCaches(): Promise<LootCache[]>;
    discoverLootCache(tier: bigint): Promise<DiscoverCacheResult>;
    processCache(cacheId: bigint): Promise<ModifierInstance>;
    getAllLandsPublic(): Promise<PublicLandInfo[]>;
    getLandDataById(landId: bigint): Promise<Option<LandData>>;
    adminGetLandData(user: Principal): Promise<LandData[] | null>;
    setMarketplaceCanister(marketplace: Principal): Promise<void>;
    setGovernanceCanister(governance: Principal): Promise<void>;
    setTokenCanister(token: Principal): Promise<void>;
    getLandOwner(landId: bigint): Promise<Principal | null>;
    transferLand(to: Principal, landId: bigint): Promise<boolean>;
    transferModifier(from: Principal, to: Principal, modifierInstanceId: bigint): Promise<boolean>;
    adminSetAllModifiers(modifier_list: Modifier[]): Promise<void>;
    getAllModifiers(): Promise<Modifier[]>;
    getModifierById(mod_id: bigint): Promise<Modifier | null>;
    getModifiersByTier(tier: bigint): Promise<Modifier[]>;
    assignCallerUserRole(user: Principal, role: string): Promise<void>;
    openCache(cacheId: bigint): Promise<any>;
    useBooster(kind: any): Promise<void>;
    getFullInventory(): Promise<any>;
    // Built-in marketplace
    list_item(itemId: bigint, itemType: any, price: bigint): Promise<bigint>;
    buy_item(listingId: bigint): Promise<boolean>;
    cancelListing(listingId: bigint): Promise<boolean>;
    getAllActiveListings(): Promise<any[]>;
    getUserListings(user: Principal): Promise<any[]>;
    getActiveListing(listingId: bigint): Promise<any | null>;
    // Governance
    gStakeTokens(amount: bigint): Promise<any>;
    gUnstakeTokens(amount: bigint): Promise<void>;
    gClaimVestedRewards(): Promise<bigint>;
    gGetMyStakeInfo(): Promise<any>;
    gGetStakedBalance(p: Principal): Promise<bigint>;
    gGetTotalWeightedStake(): Promise<bigint>;
    gReceiveIncome(amount: bigint): Promise<void>;
    gGetTreasuryBalance(): Promise<bigint>;
    gGetDeveloperFund(): Promise<bigint>;
    gGetInsuranceReserve(): Promise<bigint>;
    gCreateProposal(title: string, description: string, category: string): Promise<bigint>;
    gVote(proposalId: bigint, choice: boolean): Promise<any>;
    gGetAllProposals(): Promise<any[]>;
    gGetActiveProposals(): Promise<any[]>;
    gGetMyVotes(): Promise<any[]>;
    gGetLeaderboard(limit: bigint): Promise<any[]>;
    gCalcWeight(p: Principal): Promise<bigint>;
    gAdminCloseProposal(proposalId: bigint): Promise<void>;
    gAdminWithdrawTreasury(amount: bigint): Promise<void>;
}

function fromCandidOpt<T>(opt: [] | [T]): Option<T> {
    if (opt.length === 0) return { __kind__: "None" };
    return { __kind__: "Some", value: opt[0] };
}

function fromCandidVariant(v: Record<string, any>): any {
    const key = Object.keys(v)[0];
    const value = v[key];
    if (value === null || value === undefined || (typeof value === 'object' && Object.keys(value).length === 0)) {
        return { __kind__: key };
    }
    return { __kind__: key, [key]: value };
}

export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getLandData(): Promise<LandData[]> {
        return this.actor.getLandData();
    }
    async getLandDataQuery(): Promise<LandData[] | null> {
        const result = await this.actor.getLandDataQuery();
        if (!result || result.length === 0) return null;
        return result[0];
    }
    async getCallerUserRole(): Promise<string> {
        const result = await this.actor.getCallerUserRole();
        return Object.keys(result)[0];
    }
    async isCallerAdmin(): Promise<boolean> {
        return this.actor.isCallerAdmin();
    }
    async initializeAccessControl(): Promise<void> {
        try {
            await this.actor.initializeAccessControl();
        } catch (e) {
            console.warn("initializeAccessControl:", e);
        }
    }
    async claimRewards(landId: bigint): Promise<ClaimResult> {
        const result = await this.actor.claimRewards(landId);
        return fromCandidVariant(result);
    }
    async upgradePlot(landId: bigint, cost: bigint): Promise<UpgradeResult> {
        const result = await this.actor.upgradePlot(landId, cost);
        return fromCandidVariant(result);
    }
    async applyModifier(modifierInstanceId: bigint, landId: bigint): Promise<void> {
        await this.actor.applyModifier(modifierInstanceId, landId);
    }
    async removeModifier(landId: bigint, modifierInstanceId: bigint): Promise<void> {
        await (this.actor as any).removeModifier(landId, modifierInstanceId);
    }
    async mintLand(): Promise<LandData> {
        return this.actor.mintLand();
    }
    async getTopLands(limit: bigint): Promise<TopLandEntry[]> {
        return this.actor.getTopLands(limit);
    }
    async getMyModifierInventory(): Promise<ModifierInstance[]> {
        return (this.actor as any).getMyModifierInventory();
    }
    async getMyLootCaches(): Promise<LootCache[]> {
        return this.actor.getMyLootCaches();
    }
    async discoverLootCache(tier: bigint): Promise<DiscoverCacheResult> {
        const result = await this.actor.discoverLootCache(tier);
        return fromCandidVariant(result);
    }
    async processCache(cacheId: bigint): Promise<ModifierInstance> {
        return this.actor.processCache(cacheId);
    }
    async getAllLandsPublic(): Promise<PublicLandInfo[]> {
        return (this.actor as any).getAllLandsPublic();
    }
    async getLandDataById(landId: bigint): Promise<Option<LandData>> {
        const result = await (this.actor as any).getLandDataById(landId);
        return fromCandidOpt(result);
    }
    async adminGetLandData(user: Principal): Promise<LandData[] | null> {
        const result = await (this.actor as any).adminGetLandData(user);
        return result.length > 0 ? result[0] : null;
    }
    async setMarketplaceCanister(marketplace: Principal): Promise<void> {
        await (this.actor as any).setMarketplaceCanister(marketplace);
    }
    async setGovernanceCanister(governance: Principal): Promise<void> {
        await (this.actor as any).setGovernanceCanister(governance);
    }
    async setTokenCanister(token: Principal): Promise<void> {
        await (this.actor as any).setTokenCanister(token);
    }
    async getLandOwner(landId: bigint): Promise<Principal | null> {
        const result = await (this.actor as any).getLandOwner(landId);
        return result.length > 0 ? result[0] : null;
    }
    async transferLand(to: Principal, landId: bigint): Promise<boolean> {
        return (this.actor as any).transferLand(to, landId);
    }
    async transferModifier(from: Principal, to: Principal, modifierInstanceId: bigint): Promise<boolean> {
        return (this.actor as any).transferModifier(from, to, modifierInstanceId);
    }
    async adminSetAllModifiers(modifier_list: Modifier[]): Promise<void> {
        await (this.actor as any).adminSetAllModifiers(modifier_list);
    }
    async getAllModifiers(): Promise<Modifier[]> {
        return (this.actor as any).getAllModifiers();
    }
    async getModifierById(mod_id: bigint): Promise<Modifier | null> {
        const result = await (this.actor as any).getModifierById(mod_id);
        return result.length > 0 ? result[0] : null;
    }
    async getModifiersByTier(tier: bigint): Promise<Modifier[]> {
        return (this.actor as any).getModifiersByTier(tier);
    }
    async assignCallerUserRole(user: Principal, role: string): Promise<void> {
        await (this.actor as any).assignCallerUserRole(user, role);
    }
    async openCache(cacheId: bigint): Promise<any> {
        return (this.actor as any).openCache(cacheId);
    }
    async useBooster(kind: any): Promise<void> {
        await (this.actor as any).useBooster(kind);
    }
    async getFullInventory(): Promise<any> {
        return (this.actor as any).getFullInventory();
    }
    async list_item(itemId: bigint, itemType: any, price: bigint): Promise<bigint> {
        return (this.actor as any).list_item(itemId, itemType, price);
    }
    async buy_item(listingId: bigint): Promise<boolean> {
        return (this.actor as any).buy_item(listingId);
    }
    async cancelListing(listingId: bigint): Promise<boolean> {
        return (this.actor as any).cancelListing(listingId);
    }
    async getAllActiveListings(): Promise<any[]> {
        return (this.actor as any).getAllActiveListings();
    }
    async getUserListings(user: Principal): Promise<any[]> {
        return (this.actor as any).getUserListings(user);
    }
    async getActiveListing(listingId: bigint): Promise<any | null> {
        return (this.actor as any).getActiveListing(listingId);
    }
    async gStakeTokens(amount: bigint): Promise<any> {
        return (this.actor as any).gStakeTokens(amount);
    }
    async gUnstakeTokens(amount: bigint): Promise<void> {
        await (this.actor as any).gUnstakeTokens(amount);
    }
    async gClaimVestedRewards(): Promise<bigint> {
        return (this.actor as any).gClaimVestedRewards();
    }
    async gGetMyStakeInfo(): Promise<any> {
        return (this.actor as any).gGetMyStakeInfo();
    }
    async gGetStakedBalance(p: Principal): Promise<bigint> {
        return (this.actor as any).gGetStakedBalance(p);
    }
    async gGetTotalWeightedStake(): Promise<bigint> {
        return (this.actor as any).gGetTotalWeightedStake();
    }
    async gReceiveIncome(amount: bigint): Promise<void> {
        await (this.actor as any).gReceiveIncome(amount);
    }
    async gGetTreasuryBalance(): Promise<bigint> {
        return (this.actor as any).gGetTreasuryBalance();
    }
    async gGetDeveloperFund(): Promise<bigint> {
        return (this.actor as any).gGetDeveloperFund();
    }
    async gGetInsuranceReserve(): Promise<bigint> {
        return (this.actor as any).gGetInsuranceReserve();
    }
    async gCreateProposal(title: string, description: string, category: string): Promise<bigint> {
        return (this.actor as any).gCreateProposal(title, description, category);
    }
    async gVote(proposalId: bigint, choice: boolean): Promise<any> {
        return (this.actor as any).gVote(proposalId, choice);
    }
    async gGetAllProposals(): Promise<any[]> {
        return (this.actor as any).gGetAllProposals();
    }
    async gGetActiveProposals(): Promise<any[]> {
        return (this.actor as any).gGetActiveProposals();
    }
    async gGetMyVotes(): Promise<any[]> {
        return (this.actor as any).gGetMyVotes();
    }
    async gGetLeaderboard(limit: bigint): Promise<any[]> {
        return (this.actor as any).gGetLeaderboard(limit);
    }
    async gCalcWeight(p: Principal): Promise<bigint> {
        return (this.actor as any).gCalcWeight(p);
    }
    async gAdminCloseProposal(proposalId: bigint): Promise<void> {
        await (this.actor as any).gAdminCloseProposal(proposalId);
    }
    async gAdminWithdrawTreasury(amount: bigint): Promise<void> {
        await (this.actor as any).gAdminWithdrawTreasury(amount);
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
