/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}

export interface Coordinates {
    lat: number;
    lon: number;
}

export interface ModifierInstance {
    modifierInstanceId: bigint;
    modifierType: string;
    model_url: string;
    rarity_tier: bigint;
    multiplier_value: number;
}

export interface Modification {
    model_url: string;
    mod_id: bigint;
    rarity_tier: bigint;
    multiplier_value: number;
}

export interface LandData {
    landId: bigint;
    principal: Principal;
    biome: string;
    plotName: string;
    decorationURL: string | null | [];
    coordinates: Coordinates;
    cycleCharge: bigint;
    chargeCap: bigint;
    upgradeLevel: bigint;
    baseTokenMultiplier: number;
    lastClaimTime: bigint;
    lastChargeUpdate: bigint;
    attachedModifications: ModifierInstance[];
}

export interface LootCache {
    cache_id: bigint;
    owner: Principal;
    tier: bigint;
    discovered_at: bigint;
    is_opened: boolean;
}

export type DiscoverCacheResult =
    | { __kind__: "success"; success: LootCache }
    | { __kind__: "insufficientTokens"; insufficientTokens: { required: bigint; current: bigint } }
    | { __kind__: "paymentFailed"; paymentFailed: string }
    | { __kind__: "insufficientCharge"; insufficientCharge: { required: bigint; current: bigint } };

export type ClaimResult =
    | { __kind__: "success"; success: { tokensClaimed: bigint; newBalance: bigint; nextClaimTime: bigint } }
    | { __kind__: "mintFailed"; mintFailed: string }
    | { __kind__: "cooldown"; cooldown: { currentBalance: bigint; remainingTime: bigint } }
    | { __kind__: "insufficientCharge"; insufficientCharge: { required: bigint; current: bigint } };

export type UpgradeResult =
    | { __kind__: "maxLevelReached" }
    | { __kind__: "success"; success: { newLevel: bigint; remainingTokens: bigint } }
    | { __kind__: "insufficientTokens"; insufficientTokens: { required: bigint; current: bigint } };

export interface UserProfile {
    name: string;
}

export type Time = bigint;

export interface TopLandEntry {
    upgradeLevel: bigint;
    principal: Principal;
    tokenBalance: bigint;
    plotName: string;
    biome: string;
    landId: bigint;
}

export interface PublicLandInfo {
    landId: bigint;
    biome: string;
    principal: Principal;
}

export interface backendInterface {
    getLandData(): Promise<LandData[]>;
    getLandDataQuery(): Promise<LandData[]>;
    getUserProfile(principal: Principal): Promise<Option<UserProfile>>;
    getCallerUserProfile(): Promise<Option<UserProfile>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    getCallerUserRole(): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    claimRewards(landId: bigint): Promise<ClaimResult>;
    upgradePlot(landId: bigint, cost: bigint): Promise<UpgradeResult>;
    updatePlotName(landId: bigint, name: string): Promise<void>;
    updateDecoration(landId: bigint, url: string): Promise<void>;
    applyModifier(modifierInstanceId: bigint, landId: bigint): Promise<void>;
    removeModifier(landId: bigint, modifierInstanceId: bigint): Promise<void>;
    mintLand(): Promise<unknown>;
    getTopLands(limit: bigint): Promise<TopLandEntry[]>;
    getMyModifications(): Promise<Modification[]>;
    getMyModifierInventory(): Promise<ModifierInstance[]>;
    getMyLootCaches(): Promise<LootCache[]>;
    discoverLootCache(tier: bigint): Promise<DiscoverCacheResult>;
    processCache(cacheId: bigint): Promise<ModifierInstance>;
    getTokenBalance(): Promise<bigint>;
    getCanisterTokenBalance(): Promise<bigint>;
    debugTokenBalance(): Promise<void>;
    debugCanisterBalance(): Promise<void>;
    getStakedBalance(): Promise<bigint>;
    stakeTokens(amount: bigint): Promise<unknown>;
    getAllActiveProposals(): Promise<unknown[]>;
    createProposal(args: { title: string; description: string }): Promise<bigint>;
    vote(args: { proposalId: bigint; choice: boolean }): Promise<unknown>;
    getAllLandsPublic(): Promise<PublicLandInfo[]>;
}

function fromCandidOpt<T>(opt: [] | [T]): Option<T> {
    if (opt.length === 0) return { __kind__: "None" };
    return { __kind__: "Some", value: opt[0] };
}

function fromCandidVariant(v: Record<string, any>): any {
    const key = Object.keys(v)[0];
    const value = v[key];
    if (value === null || value === undefined || (typeof value === 'object' && Object.keys(value).length === 0)) {
        return { __kind__: key };
    }
    return { __kind__: key, [key]: value };
}

function convertLandData(land: any): LandData {
    return {
        ...land,
        decorationURL: land.decorationURL.length > 0 ? land.decorationURL[0] : null,
    };
}

export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getLandData(): Promise<LandData[]> {
        const result = await this.actor.getLandData();
        return result.map(convertLandData);
    }
    async getLandDataQuery(): Promise<LandData[]> {
        const result = await this.actor.getLandDataQuery();
        if (result.length === 0) return [];
        return result[0].map(convertLandData);
    }
    async getUserProfile(principal: Principal): Promise<Option<UserProfile>> {
        const result = await this.actor.getUserProfile(principal);
        return fromCandidOpt(result);
    }
    async getCallerUserProfile(): Promise<Option<UserProfile>> {
        const result = await this.actor.getCallerUserProfile();
        return fromCandidOpt(result);
    }
    async saveCallerUserProfile(profile: UserProfile): Promise<void> {
        await this.actor.saveCallerUserProfile(profile);
    }
    async getCallerUserRole(): Promise<string> {
        const result = await this.actor.getCallerUserRole();
        return Object.keys(result)[0];
    }
    async isCallerAdmin(): Promise<boolean> {
        return this.actor.isCallerAdmin();
    }
    async initializeAccessControl(): Promise<void> {
        try {
            await this.actor.initializeAccessControl();
        } catch (e) {
            console.warn("initializeAccessControl:", e);
        }
    }
    async claimRewards(landId: bigint): Promise<ClaimResult> {
        const result = await this.actor.claimRewards(landId);
        return fromCandidVariant(result);
    }
    async upgradePlot(landId: bigint, cost: bigint): Promise<UpgradeResult> {
        const result = await this.actor.upgradePlot(landId, cost);
        return fromCandidVariant(result);
    }
    async updatePlotName(landId: bigint, name: string): Promise<void> {
        await this.actor.updatePlotName(landId, name);
    }
    async updateDecoration(landId: bigint, url: string): Promise<void> {
        await this.actor.updateDecoration(landId, url);
    }
    async applyModifier(modifierInstanceId: bigint, landId: bigint): Promise<void> {
        await this.actor.applyModifier(modifierInstanceId, landId);
    }
    async removeModifier(landId: bigint, modifierInstanceId: bigint): Promise<void> {
        await (this.actor as any).removeModifier(landId, modifierInstanceId);
    }
    async mintLand(): Promise<unknown> {
        return this.actor.mintLand();
    }
    async getTopLands(limit: bigint): Promise<TopLandEntry[]> {
        return this.actor.getTopLands(limit);
    }
    async getMyModifications(): Promise<Modification[]> {
        return this.actor.getMyModifications();
    }
    async getMyModifierInventory(): Promise<ModifierInstance[]> {
        return [];
    }
    async getMyLootCaches(): Promise<LootCache[]> {
        return this.actor.getMyLootCaches();
    }
    async discoverLootCache(tier: bigint): Promise<DiscoverCacheResult> {
        const result = await this.actor.discoverLootCache(tier);
        return fromCandidVariant(result);
    }
    async processCache(cacheId: bigint): Promise<ModifierInstance> {
        return this.actor.processCache(cacheId);
    }
    async getTokenBalance(): Promise<bigint> {
        return this.actor.getCurrentCbrBalance();
    }
    async getCanisterTokenBalance(): Promise<bigint> { return 0n; }
    async debugTokenBalance(): Promise<void> {}
    async debugCanisterBalance(): Promise<void> {}
    async getStakedBalance(): Promise<bigint> { return 0n; }
    async stakeTokens(_amount: bigint): Promise<unknown> { return null; }
    async getAllActiveProposals(): Promise<unknown[]> { return []; }
    async createProposal(_args: { title: string; description: string }): Promise<bigint> { return 0n; }
    async vote(_args: { proposalId: bigint; choice: boolean }): Promise<unknown> { return null; }
    async getAllLandsPublic(): Promise<PublicLandInfo[]> { return (this.actor as any).getAllLandsPublic(); }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
